# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-05-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cloginid', models.CharField(blank=True, max_length=10, null=True)),
                ('cpassword', models.CharField(blank=True, max_length=45, null=True)),
                ('cname', models.CharField(blank=True, max_length=10, null=True)),
                ('ctel', models.CharField(blank=True, max_length=45, null=True)),
                ('caddress', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('companyid', models.CharField(blank=True, max_length=10, null=True)),
                ('jobinfo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'jobhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('sex', models.CharField(max_length=32)),
                ('c_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'login_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('resumeid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=True, max_length=10, null=True)),
                ('sgrade', models.IntegerField(blank=True, null=True)),
                ('sschool', models.CharField(blank=True, max_length=45, null=True)),
                ('smajor', models.CharField(blank=True, max_length=45, null=True)),
                ('eduinfo', models.TextField(blank=True, null=True)),
                ('interninfo', models.TextField(blank=True, null=True)),
                ('skillinfo', models.TextField(blank=True, null=True)),
                ('selfintro', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'resume',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('seminarid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('companyid', models.CharField(blank=True, max_length=10, null=True)),
                ('stime', models.DateTimeField(blank=True, null=True)),
                ('splace', models.CharField(blank=True, max_length=45, null=True)),
                ('stheme', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'seminar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seminarhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'seminarhistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sloginid', models.CharField(blank=True, max_length=10, null=True)),
                ('spassword', models.CharField(blank=True, max_length=45, null=True)),
                ('sname', models.CharField(blank=True, max_length=10, null=True)),
                ('sgrade', models.IntegerField(blank=True, null=True)),
                ('sschool', models.CharField(blank=True, max_length=45, null=True)),
                ('smajor', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
    ]
