# Generated by Django 3.0.6 on 2020-05-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interestid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('number_1', models.FloatField(blank=True, db_column='1', null=True)),
                ('number_2', models.FloatField(blank=True, db_column='2', null=True)),
                ('number_3', models.FloatField(blank=True, db_column='3', null=True)),
            ],
            options={
                'db_table': 'interest',
                'managed': False,
            },
        ),
    ]
